---
abstract: 'Use WebService::Solr in your Catalyst application'
author:
  - 'Brian Cassidy <bricas@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-WebService-Solr
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 5.7000
  WebService::Solr: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
